---
title: "Lecture 5 (Data Wrangling II) - Data Manipulation"
author: "CJ Snyder"
date: "9/19/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
```

# Uploading Datasets: litters & pups
```{r}
options(tibble.print_min = 3)

litters_data = read_csv("./data/FAS_litters.csv",
  col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data/FAS_pups.csv",
  col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)
```

# Beginning Data Manipulation
## _select_ Function
```{r}
select(litters_data, group, litter_number, gd0_weight, pups_born_alive) #Specifies variables to keep

select(litters_data, group, litter_number, gd0_weight, starts_with("pups")) #'starts_with' allows you to select all variables that starts with phrase/word

select(litters_data, group:gd_of_birth) #Indicates RANGE of variables to keep (inclusive)

select (litters_data, litter_number, group, everything()) #'everything()' keeps all variables

# The way in which you select variables ALSO REORDERS THEM!!

select(litters_data, -pups_survive) #Removes specified column 'pups_survive'


select(litters_data, GROUP = group, LiTtEr_NuMbEr = litter_number) #Renames variables, but only as part of the select function

rename(litters_data, GROUP = group, LiTtEr_NuMbEr = litter_number) #Renames variables

# The litters_data is NOT modified until it is saved into a new data frame
litters_selected = select(litters_data, group:gd_of_birth)
```

### Example
```{r}
select(pups_data, litter_number:pd_ears)
```

## _filter_ Function 
```{r}
filter(litters_data, group == 'Mod8')

filter(litters_data, gd_of_birth == 20)

filter(litters_data, gd_of_birth < 20)

filter(litters_data, gd_of_birth != 20)

filter(litters_data, pups_born_alive < 6, group =="Con7")

filter(litters_data, group == "Mod8" | group == "Con7") # OR statement

filter(litters_data, group %in% c("Mod8", "Con7")) # Equivalent to OR statement

# Does not have good range statements, will need to create the range ends with two statements

drop_na(litters_data) # Automatically removes ALL observations with missing data

drop_na(litters_data, gd0_weight) # Removes missing observations with missing 'gd0_weight' value
```

### Example 
```{r}
filter(pups_data, sex == 1)

filter(pups_data, sex ==2, pd_walk < 11)
```

## _mutate_ Function
```{r}
mutate(litters_data, 
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group),
  group = str_to_upper(group)
  )
# Can mutate multiple variables at the same time
```

## _arrange_ Function
```{r}
arrange(litters_data, pups_born_alive)

arrange(litters_data, desc(pups_born_alive))

arrange(litters_data, pups_born_alive, gd0_weight)
# Arranges in order of variable, first pups born alive, then initial weight
```

# Pulling Everything Together...through _piping_!!
```{r}
litters_data = 
  read_csv("./data/FAS_litters.csv") %>% 
  janitor::clean_names() %>% 
  select(-pups_survive) %>% 
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>% 
  drop_na(gd0_weight)

#Ctrl+Shift+M keybind for %>%
```


```{r, eval = FALSE}
litters_data %>%  view()

litters_data %>% pull(gd0_weight) %>% mean 
```



